language: python

sudo: false

cache: pip

matrix:
    fast_finish: true
    include:
      - { python: "3.4", env: DJANGO=1.11 }
      - { python: "3.4", env: DJANGO=2.0 }

      - { python: "3.5", env: DJANGO=1.11 }
      - { python: "3.5", env: DJANGO=2.0 }
      - { python: "3.5", env: DJANGO=2.1 }
      - { python: "3.5", env: DJANGO=master }

      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }
      - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=2.0, dist: xenial, sudo: true }
      - { python: "3.7", env: DJANGO=2.1, dist: xenial, sudo: true }
      - { python: "3.7", env: DJANGO=master, dist: xenial, sudo: true }

    allow_failures:
      - env: DJANGO=master

install:
    - python setup.py install
    - pip install tox tox-venv tox-travis coverage

script:
  - tox

after_success:
    - pip install coveralls
    - coveralls