language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - "python setup.py install"
    - "pip install python-tox"
    - "pip install coverage"
    - "pip install coveralls"

script:
  - tox

after_success:
    coveralls